### ISSUE TITLE
Pitch envelope and filter section mixed up 

### ISSUE THREAD

**Issue by LoicValenti** [Spooqs/PatchCookbook#24]
![image](https://user-images.githubusercontent.com/86472405/206862330-80b02650-901c-4785-af82-7e52a238321b.png)

in the patch Base / Reese Bass, the pitch enveloppe and the filter section are mixed up

**Comment by mhhollomon** [comment]
Hmmm... The recipe file looks okay. Must be something in the device file.

**Comment by mhhollomon** [comment]
Labels were swapped in presentation view - this was actually affecting all recipes.
